server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8767/eureka/
spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializers: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer