server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8767/eureka/

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-serializers: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: receiver-group
      auto-offset-reset: earliest